import{a as w,S,i as c}from"./assets/vendor-CrlV4O_2.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const q="50383769-6461d4d81fbd57ed3efc96c78",v="https://pixabay.com/api/";async function O(r,t=1){try{return(await w.get(v,{params:{key:q,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}})).data}catch(n){throw n}}const $=new S(".gallery a",{captionsData:"alt",captionDelay:250}),y=document.querySelector(".gallery");document.querySelector(".loader");function E(r){const t=r.map(({webformatURL:n,largeImageURL:s,tags:e,likes:o,views:i,comments:b,downloads:L})=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${s}">
        <img class="gallery-image" src="${n}" alt="${e}" />
      </a>
      <div class="info">
        <p><b>Likes:</b> ${o}</p>
        <p><b>Views:</b> ${i}</p>
        <p><b>Comments:</b> ${b}</p>
        <p><b>Downloads:</b> ${L}</p>
      </div>
    </li>
  `).join("");y.insertAdjacentHTML("beforeend",t),$.refresh()}function M(){document.querySelector(".loader").style.display="block"}function u(){document.querySelector(".loader").style.display="none"}function d(){y.innerHTML=""}function P(){document.querySelector(".load-more").style.display="block"}function p(){document.querySelector(".load-more").style.display="none"}const g=document.querySelector(".form"),f=g.elements["search-text"],x=document.querySelector(".load-more");let a=1,l="",m=0;const B=15;async function h(r=!1){if(l)try{M(),r&&(a=1);const t=await O(l,a);if(u(),t.total===0||t.hits.length===0){c.warning({title:"Oops!",message:"No images found. Try another word!",position:"topRight"}),d(),p();return}if(r&&d(),E(t.hits),m=Math.ceil(t.totalHits/B),a<m?P():(p(),c.info({title:"Oops!",message:"We are sorry, but you have reached the end of search results.",position:"topRight"})),!r){const{height:n}=document.querySelector(".gallery").lastElementChild.getBoundingClientRect();window.scrollBy({top:n*2,behavior:"smooth"})}}catch(t){u(),c.error({title:"Error",message:`Something went wrong: ${t.message}`,position:"topRight"})}}g.addEventListener("submit",r=>{r.preventDefault(),l=f.value.trim(),l&&(h(!0),f.value="")});x.addEventListener("click",()=>{a+=1,h(!1)});
//# sourceMappingURL=index.js.map
